namespace nnCitiesShared.Translation;

/// <summary>
/// A class that has the keys of the translation string.
/// This code was automatically generated by T4.
/// </summary>
public static partial class KeyStrings
{

    /// <summary>
    /// Source: Reset <br/>
    /// Context: 
    /// </summary>
    public const string RESET = "RESET";

    /// <summary>
    /// Source: Default <br/>
    /// Context: 
    /// </summary>
    public const string DEFAULT = "DEFAULT";

    /// <summary>
    /// Source: Not set <br/>
    /// Context: 
    /// </summary>
    public const string NOT_SET = "NOT_SET";

    /// <summary>
    /// Source: Reset to Default <br/>
    /// Context: 
    /// </summary>
    public const string RESET_TO_DEFAULT = "RESET_TO_DEFAULT";

    /// <summary>
    /// Source: Reset to Vanilla <br/>
    /// Context: 
    /// </summary>
    public const string RESET_TO_VANILLA = "RESET_TO_VANILLA";

    /// <summary>
    /// Source: Apply <br/>
    /// Context: 
    /// </summary>
    public const string APPLY = "APPLY";

    /// <summary>
    /// Source: Support <br/>
    /// Context: 
    /// </summary>
    public const string SUPPORT = "SUPPORT";

    /// <summary>
    /// Source: Enable <br/>
    /// Context: 
    /// </summary>
    public const string ENABLE = "ENABLE";

    /// <summary>
    /// Source: Disable <br/>
    /// Context: 
    /// </summary>
    public const string DISABLE = "DISABLE";

    /// <summary>
    /// Source: Vanilla <br/>
    /// Context: 
    /// </summary>
    public const string VANILLA = "VANILLA";

    /// <summary>
    /// Source: Custom <br/>
    /// Context: 
    /// </summary>
    public const string CUSTOM = "CUSTOM";

    /// <summary>
    /// Source: Steam Workshop Page <br/>
    /// Context: 
    /// </summary>
    public const string STEAM_WORKSHOP_PAGE = "STEAM_WORKSHOP_PAGE";

    /// <summary>
    /// Source: Github Repository <br/>
    /// Context: 
    /// </summary>
    public const string GITHUB_REPOSITORY = "GITHUB_REPOSITORY";

    /// <summary>
    /// Source: Discord Server <br/>
    /// Context: 
    /// </summary>
    public const string DISCORD_SERVER = "DISCORD_SERVER";

    /// <summary>
    /// Source: Close <br/>
    /// Context: 
    /// </summary>
    public const string CLOSE_BTN = "CLOSE_BTN";

    /// <summary>
    /// Source: Minimize <br/>
    /// Context: 
    /// </summary>
    public const string MINIMIZE_BTN = "MINIMIZE_BTN";

    /// <summary>
    /// Source: Localization <br/>
    /// Context: 
    /// </summary>
    public const string GROUP_LOCALIZATION = "GROUP_LOCALIZATION";

    /// <summary>
    /// Source: Select Language <br/>
    /// Context: 
    /// </summary>
    public const string SELECT_LANGUAGE = "SELECT_LANGUAGE";

    /// <summary>
    /// Source: Use game language <br/>
    /// Context: 
    /// </summary>
    public const string USE_GAME_LANGUAGE = "USE_GAME_LANGUAGE";
}